language: php

php:
  - 7.4
  - 8.0
  - 8.1
  - 8.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
 - nvm install 7
 - nvm use 7

install:
  - yes '' | pecl install solr
  - cd ../..
  - git clone --depth 1 https://github.com/omeka/omeka-s.git
  - git clone --depth 1 https://gitlab.com/Daniel-KM/Omeka-S-module-HistoryLog.git omeka-s/modules/HistoryLog
  - cp -a $(readlink -e $(cd -)) omeka-s/modules/HistoryLog
  - cd omeka-s

before_script:
  - mysql -e "create database IF NOT EXISTS omeka_test;" -uroot
  - sed -i 's/^host.*/host = "localhost"/' application/test/config/database.ini
  - sed -i 's/^user.*/user = "root"/' application/test/config/database.ini
  - sed -i 's/^dbname.*/dbname = "omeka_test"/' application/test/config/database.ini
  - cd modules/SearchSolr
  - composer install

script:
  - ../../vendor/bin/phpunit
  - ../../vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no --allow-risky=yes
