<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $entityName
 * @var int $entityId
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $entity
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation[] $historyEvents
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation[] $resources
 */

$plugins = $this->getHelperPluginManager();
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
?>

<?php // TODO Display pagination? ?>

<table class="history-log tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $translate('Details') ?></th>
            <th><?= $translate('Operation') ?></th>
            <th><?= $translate('Date') ?></th>
            <th><?= $translate('User') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($historyEvents as $historyEvent):
            $isUndeletable = $historyEvent->isEventToUndelete();
        ?>
        <tr>
            <td>
                <?= nl2br($historyEvent->displayChanges(), true) ?>
            </td>
            <td class="operation operation-<?= $historyEvent->operation() ?>">
                <?= $historyEvent->displayOperation() ?>
                <?php if ($isUndeletable): ?>
                <div class="history-log-undelete">
                    <a href="<?= $historyEvent->adminUrl('undelete') ?>" class="history-log-process button red"><?= $escape($translate('Undo')) ?></a>
                </div>
                <?php endif; ?>
            </td>
            <td><?= $i18n->dateFormat($historyEvent->created()) ?></td>
            <td><?= $historyEvent->displayUser() ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
