<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation $historyEvent
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation $resource
 * @var array $data
 *
 * @var bool $includeHeaders
 */

$changes = $historyEvent->changes();
If (!count($changes)) return;

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$translate = $plugins->get('translate');
?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $translate('Data') ?></th>
            <th><?= $translate('Field') ?></th>
            <th><?= $translate('Action') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($historyEvent->changes() as $historyChange): ?>
        <tr>
            <td>
                <?= $partial('common/history-log-change-data', ['historyChange' => $historyChange, 'resource' => $historyChange]) ?>
            </td>
            <td>
                <?= $historyChange->field() ?>
            </td>
            <td>
                <?= $historyChange->displayAction() ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
