<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation $historyEvent
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation $resource
 * @var array $data
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
?>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <td><?= $translate('Action') ?></td>
            <td><?= $translate('Field') ?></td>
            <td><?= $translate('Data') ?></td>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($historyEvent->changes() as $historyChange): ?>
        <tr>
            <td>
                <?= $historyChange->displayAction() ?>
            </td>
            <td>
                <?= $historyChange->field() ?>
            </td>
            <td>
                <?= $escape(json_encode($historyChange->data(), 448)) ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
