<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation[] $historyEvents
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation[] $resources
 * @var string $returnQuery
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$userIsAllowed = $plugins->get('userIsAllowed');

$this->headLink()
    ->appendStylesheet($assetUrl('css/history-log-admin.css', 'HistoryLog'));

$this->htmlElement('body')->appendAttribute('class', 'history-logs history-events browse');
?>

<?= $this->pageTitle('', 1, $translate('History logs')) ?>

<?= $this->searchFilters() ?>

<div class="browse-controls">
    <?= $this->pagination() ?>
    <?= $hyperlink($translate('Advanced search'), $url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']) ?>
    <?= $this->browse()->renderSortSelector('history_events') ?>
</div>

<div id="page-actions">
    <?php /* // TODO Rights to reset  or to undelete a resource. Which adapter? ?>
    <?php if ($userIsAllowed('Omeka\Api\Adapter\history eventAdapter', 'create')): ?>
    <?= $hyperlink($translate('Reset entity'), $url(null, ['action' => 'add'], true), ['class' => 'button']) ?>
    <?= $hyperlink($translate('Undelete entity'), $url(null, ['action' => 'add'], true), ['class' => 'button']) ?>
    <?php endif; ?>
    */ ?>
</div>

<?php $this->trigger('view.browse.before'); ?>

<?php if ($historyEvents): ?>
<form method="post" id="batch-form" class="disable-unsaved-warning">
    <?php /*
    <?php if ($userIsAllowed('Omeka\Api\Adapter\history eventAdapter', 'batch_update')): ?>
    <div class="batch-inputs">
        <select class="batch-actions-select" aria-label="<?= $translate('Batch actions') ?>">
            <option value="default"><?= $translate('Batch actions') ?></option>
            <option value="update-selected" disabled="true"><?= $translate('Edit selected') ?></option>
            <?php if ($userIsAllowed('Omeka\Api\Adapter\history eventAdapter', 'batch_update_all')): ?>
            <option value="update-all"><?= $translate('Edit all') ?></option>
            <?php endif; ?>
            <option value="delete-selected" disabled="true"><?= $translate('Delete selected') ?></option>
            <?php if ($userIsAllowed('Omeka\Api\Adapter\history eventAdapter', 'batch_delete_all')): ?>
            <option value="delete-all"><?= $translate('Delete all') ?></option>
            <?php endif; ?>
        </select>
        <div class="batch-actions">
            <button type="button" class="default active" disabled="true"><?= $translate('Go') ?></button>
            <input type="submit" class="update-selected" name="update_selected" value="<?= $translate('Go') ?>" formaction="<?= $escape($url(null, ['action' => 'batch-edit'], ['query' => $returnQuery], true)) ?>">
            <input type="submit" class="update-all" name="update_all" value="<?= $translate('Go') ?>" formaction="<?= $escape($url(null, ['action' => 'batch-edit-all'], ['query' => $returnQuery], true)) ?>">
            <input type="hidden" name="query" class="batch-query" value="<?= $escape(json_encode($this->params()->fromQuery())) ?>">
            <a class="delete button sidebar-content delete-selected" data-sidebar-selector="#sidebar-delete-selected"><?= $translate('Go') ?></a>
            <a class="delete button sidebar-content delete-all" data-sidebar-selector="#sidebar-delete-all"><?= $translate('Go') ?></a>
        </div>
    </div>
    <?php endif; ?>
    */ ?>


<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="select-all" aria-label="<?= $translate('Select all') ?>">
                <?= $translate('Details') ?>
            </th>
            <?= $this->browse()->renderHeaderRow('history_events') ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($historyEvents as $historyEvent): ?>
        <tr>
            <td>
                <?php /*
                <?php if ($userIsAllowed('Omeka\Api\Adapter\history eventAdapter', 'batch_update') && ($historyEvent->userIsAllowed('update') || $historyEvent->userIsAllowed('delete'))): ?>
                <input type="checkbox" name="resource_ids[]" value="<?= $historyEvent->id() ?>" aria-label="<?= $translate('Select history event') ?>">
                <?php endif; ?>
                */ ?>
                <?= $this->partial('common/history-log-changes', [
                    'historyEvent' => $historyEvent,
                    'resource' => $historyEvent,
                ]) ?>
                <?php /*
                <?= $historyEvent->link(sprintf('#%d', $historyEvent->id())) ?>
                <ul class="actions">
                    <?php if ($historyEvent->userIsAllowed('update')): ?>
                    <li><?= $historyEvent->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $translate('Edit'),
                    ]) ?></li>
                    <?php endif; ?>
                    <?php if ($historyEvent->userIsAllowed('delete')): ?>
                    <li><?= $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $historyEvent->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $translate('Delete'),
                    ]) ?></li>
                    <?php endif; ?>
                    <li><?= $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $historyEvent->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $translate('Details'),
                    ]) ?></li>
                </ul>
                */ ?>
            </td>
            <?= $this->browse()->renderContentRow('history_events', $historyEvent) ?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<?php /*
<div id="sidebar" class="sidebar">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content"></div>
</div>
<div id="sidebar-delete-selected" class="sidebar">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?= $translate('Delete history events') ?></h3>
            <p><?= $translate('Are you sure you would like to delete the selected history events?') ?></p>
            <p class="error"><?= sprintf(
                $translate('%1$s: this action will permanently delete %2$s history events and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                '<strong><span id="delete-selected-count"></span></strong>'
            ) ?></p>
            <?= $this->form($this->formDeleteSelected) ?>
        </div>
    </div>
</div>
<div id="sidebar-delete-all" class="sidebar">
    <?= $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]) ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?= $translate('Delete history events') ?></h3>
            <p><?= $translate('Are you sure you would like to delete all history events on all pages of this result?') ?></p>
            <p class="error"><?= sprintf(
                $translate('%1$s: this action will permanently delete %2$s history events and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
            ) ?></p>
            <label><input type="checkbox" name="confirm-delete-all-check"> <?= $translate('Are you sure?') ?></label>
            <?= $this->form($this->formDeleteAll) ?>
        </div>
    </div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
    var confirmForm = $(this);
    if ('confirm-delete-all' === this.id) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input[name="resource_ids[]"]:checked').each(function() {
            confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
        });
    }
});
$('.delete-all').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-selected'));
});
$('.delete-selected').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-all'));
    var inputs = $('input[name="resource_ids[]"]');
    $('#delete-selected-count').text(inputs.filter(':checked').length);
});
$('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
    $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
});
</script>
*/ ?>

<?php else: ?>

<div class="no-resources">
    <p><?= $translate('Omeka could not find any history logs.') ?></p>
</div>

<?php endif; ?>
