<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $entityName
 * @var int $entityId
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $entity
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation[] $historyEvents
 * @var \HistoryLog\Api\Representation\HistoryEventRepresentation[] $resources
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/history-log-admin.css', 'HistoryLog'));

$this->htmlElement('body')->appendAttribute('class', 'history-logs history-events browse history-log');
?>

<?= $this->pageTitle(sprintf($translate('Last changes for %s #%d'), $entityName, $entityId), 1, $translate('History logs')) ?>

<div id="page-actions">
    <?php if ($entity): ?>
    <?= $entity->link($translate('Show resource'), null, ['class' => 'button']) ?>
    <?php endif; ?>
</div>

<?php if ($historyEvents): ?>
    <?php if (!$entity): ?>
    <p><?= $translate('This resource was deleted.') ?></p>
    <?php endif; ?>
    <?= $this->partial('common/history-log') ?>
<?php else: ?>
    <p><?= $translate('No log for this record.') ?></p>
    <?php if (!$entity): ?>
    <p><?= $translate('This resource does not exist and is not logged.') ?></p>
    <?php endif; ?>
<?php endif; ?>
